### ISSUE TITLE
Support generating multiple thumbnails from a PDF

### ISSUE THREAD

**Issue by mlissner** [freelawproject/doctor#126]
When we finally get back to working on the Big Cases Bot, we'll probably want to be able to generate multiple thumbnails for a single PDF. The old bot would tweet with four thumbnails from the PDF. 

I guess the two ways to do this would be to either:

1. Have an API where you say which pages you want and it somehow gives you back multiple pages. (Does HTTP support this?)
2. Have an API where you say which page (singular) you want. If you don't say, it gives you page one. If you do, it gives you the page you requested.

**Comment by mlissner** [comment]
Didn't you remove this functionality in #133?

**Comment by flooie** [comment]
Yes
