### ISSUE TITLE
build deploy pipeline breaks when merging prs

### ISSUE THREAD

**Issue by trashhalo** [freelawproject/doctor#189]
Went to pull in new version after you merged #188 and noticed that the docker hub build hadn't been updated. When I check out the deploy action it seems to fail consistently on merge, missing the credentials needed to push to docker hub. https://github.com/freelawproject/doctor/actions/workflows/deploy.yml

Not sure if this is intentional but wanted to flag it.

**Comment by mlissner** [comment]
This is an annoying thing because you're not in our workspace, so your PRs don't have access to our docker secrets. We have another PR coming in shortly from a staff member, so when that comes in, we should get a good deployment. I'm going to close, but let's pick this up over Slack.
